<a href="https://colab.research.google.com/github/adlihs/PyTorch/blob/main/Tensors_The_Core_of_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors: The Core of PyTorch**

## Imports

In [1]:
import torch
import numpy as np
import pandas as pd

## 1- Tensor Creation
The first step in any machine learning pipeline is getting your data ready for the model. In PyTorch, this means looading your data into tensors.

## 1.1 From existing Data Structures
Often, your raw data will be in a common format like a Python list, a NumPy array, or a pandas DataFrame. PyTorch provides straightforward functions to convert these structures into tensors, making the data preparation stage more efficient.



*   `torch.tensor():` This function takes input such as a Python list to convert it into a tensor.

**NOTE:** The type of numbers you use matters. *If you use integers, PyTorch stores them as integers*. If you include decimals, they'll be stored as floating point values.




In [2]:
# From Python lists
x = torch.tensor([1,2,3])

print("FROM PYTHON LISTS:",x)
print("TENSOR DATA TYPE:", x.dtype)

FROM PYTHON LISTS: tensor([1, 2, 3])
TENSOR DATA TYPE: torch.int64


##

*   `torch.from_numpy():` Converts NumPy array into PyTorch tensor



In [3]:
# from Numpy array
numpy_array = np.array([[1,2,3],[4,5,6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("TENSOR FROM NUMPY:\n\n", torch_tensor_from_numpy)

TENSOR FROM NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])


##

*   **From a pandas dataframe:** Pandas is a Python library for working with data organized in rows and columns, like a CSV file or spreadsheet. A DataFrame is pandas' main data structure for storing this kind of tabular data. DataFrames are one of the most common ways to load and explore datasets in machine learning, especially when reading CSV files. There isn't a direct function to convert a DataFrame to a tensor. *The standard method is to extract the data from the DataFrame into a NumPy array using the `.values` attribute, and then convert that array into a tensor using `torch.tensor()`.*




In [5]:
# from Pandas DataFrame
# Read the data from CSV file into a DataFrame
df = pd.read_csv('/content/drive/MyDrive/PyTorch/data.csv')

# Extract the data as a NumPy array from the DataFrame
all_values = df.values

# Convert the DataFrame's values to a PyTorch tensor
tensor_from_df = torch.tensor(all_values)

print("ORIGINAL DATAFRAME:\n\n", df)
print("\nRESULTING TENSOR:\n\n", tensor_from_df)
print("\nTENSOR DATA TYPE:", tensor_from_df.dtype)

ORIGINAL DATAFRAME:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

RESULTING TENSOR:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TENSOR DATA TYPE: torch.float64


## **1.2 - With Predefined Values**
Sometimes you need to create tensors for specific purposes, like initializing a model's weights and biases before training begins. PyTorch allows you to quickly generate tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for testing and setup.



*   `torch.zeros():` Creates a tensor filled with zeros of the specific dimensions.




In [6]:
# All zeros
zeros = torch.zeros(2,3)

print("TENSOR WITH ZEROS:\n\n", zeros)

TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##

*   `torch.ones():` Creates a tensor filled with ones of the specified dimensions.




In [7]:
# All ones
ones = torch.ones(2,3)

print("TENSOR WITH ONES:\n\n", ones)

TENSOR WITH ONES:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


##

*   `torch.rand():` Generates a tensor with random numbers uniformly distributed between 0 and 1, based on the specified dimensions.

In [8]:
# Randon Numbers
random = torch.rand(2,3)

print("TENSOR WITH RANDOM NUMBERS:\n\n", random)

TENSOR WITH RANDOM NUMBERS:

 tensor([[0.9927, 0.7681, 0.7347],
        [0.3813, 0.7765, 0.4979]])


## **1.3 - From a Sequence**
For situations where you need to generate a sequence of data points, such as a range of values for testing a model's predictions, you can create a tensor directly from that sequence.



*   `torch.arange()`: Creates a 1D tensor containing a range of numbers from the specified start value to one less tahn the specified stop value, incrementing (if positive) or decrementing (if negative) by the specified `step` value




In [11]:
# Range of numbers
range_tensor = torch.arange(0,10,step=1)

print("RANGE TENSOR:\n\n", range_tensor)

RANGE TENSOR:

 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## **2- Reshaping & Manipulating**
A very common source of errors in PyTorch projects is ***a mismatch between the shape of your input data and the shape your model expects***. For instance, a model is typically designed to process a batch of data, so even if you want to make a single prediction, you must shape your input tensor to look like a batch of one. Mastering tensor reshaping is a key step toward building and debugging models effectively.

## 2.1 - Checking a Tensor's Dimensions
The first step to fixing a shape mismatch is to understand the current dimensions of your tensor. Checking the shape is your primary debugging tool. It tells you how many samples you have and how many features are in each sample.



*   `torch.Tensor.shape:` An attribute that returns a `torch.Size` object detailing the size of the tensor along each dimension.




In [12]:
# A 2D tensor
x = torch.tensor([[1,2,3],
                  [4,5,6]])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


## 2.2 - Changing a Tensor's Dimensions

Once you identify a shape mismatch, you need to correct it. ***A frequent task is adding a dimension to a single data sample to create a batch of size one for your model, or removing a dimension after a batch operation is complete***.



*   **Adding Dimension:** `torch.Tensor.unsqueeze()` inserts a new dimension at the specified index.
      * Notice how the shape will change from `[2,3]` to `[1,2,3]` and the tensor gets wrapped in an extra pair of square brakets `[]`






In [14]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Add dimension

expanded = x.unsqueeze(0) # Add dimension at index 0

print("\nTENSOR WITH ADDED DIMENSION AT INDEX 0:\n\n", expanded)
print("\nTENSOR SHAPE:", expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

TENSOR WITH ADDED DIMENSION AT INDEX 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])


##

*   **Removing Dimensions:** `torch.Tensor.squeeze()` removes dimensions of size 1.
      * *This reverses the unsqueeze operation, remooving the `1` from the shape and taking away a pair of outer square brackets.*

